spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3307/epe2
    password: '1234'
  mvc:
    contentnegotiation:
      favor-parameter: 'true'
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: epe2-back

server:
  port: '8080' 
